- platform/checkout/cisco-8000.ini
Signed-off-by: anamehra [anamehra@cisco.com](mailto:anamehra@cisco.com)
Update cisco-8000.ini to use platform release version 202205-v0.1
> Update cisco-8000.ini to use 202205-v0.1

- platform/checkout/cisco-8000.ini
Reverts Azure/sonic-buildimage-msft#12
This change should go to public branch and not this branch.
> Revert "Update cisco-8000.ini to use 202205-v0.1"

- src/sonic-py-common/tests/device_info_test.py
> Remove the test_get_platform_info tests whichis not present in

- files/build_templates/sonic_debian_extension.j2
In the PR sonic-net/sonic-utilities#2850 , for support remote access of linecards paramiko package is installed in sonic-utilities. libffi-dev needs to installed to be able to compile for armhf image
> [chassis] add libffi-dev for sonic-utilities (#15218)

- installer/x86_64/install.sh
This is to fix a cherry-pick error where some changes got left out which causes the image not able to load on pizzabox platforms failling with following messages:
```
Loading SONiC-OS OS kernel ...Loading SONiC-OS OS kernel ...
error: can't find command `linuxefi'.
error: can't find command `linuxefi'.
Loading SONiC-OS OS initial ramdisk ...Loading SONiC-OS OS initial ramdisk ...
```
> Fix Secureboot causing image load issue on pizzabox platforms

- dockers/docker-fpm-frr/base_image_files/TSA
- dockers/docker-fpm-frr/base_image_files/TSB
- dockers/docker-fpm-frr/base_image_files/TSC
TSA/B/C scripts invoke commands that require root permissions. If the user does not have sudo permissions, the scripts today execute until the command and throw a backtrace with error at the specific command. Added a check to ensure the operations check for root permissions upfront.
> [bgp]: Add sudo check for TSA/B/C command execution (#15288)

- files/build_templates/init_cfg.json.j2
Double-commit from master: https://github.com/sonic-net/sonic-buildimage/pull/16224
Enabling kdump by default for cisco-8000 by setting crashkernel cmdline arg in device installer.conf.
After bootup, sonic-kdump-config wipes crashkernel arg from /host/grub/grub.cfg, and resets USE_KDUMP in /etc/default/kdump-tools, so kdump will not be enabled on subsequent reboot.
Setting kdump enable config as part of init_cfg.json for cisco-8000 platforms.
Install SONiC image with kdump enabled by default (device/hwsku/installer.conf), then reboot.
Kdump config should persist on subsequent reboots and kdump loaded during bootup.
> Enable Kdump config by default for cisco-8000

- dockers/docker-fpm-frr/TS
- dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2
- dockers/docker-fpm-frr/frr/bgpd/templates/voq_chassis/policies.conf.j2
- dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.isolate.conf.j2
- dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.unisolate.conf.j2
- files/image_config/constants/constants.yml
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_all_isolate.conf
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_all_unisolate.conf
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_isolate.conf
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_unisolate.conf
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/param_chasiss_packet.json
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/param_front.json
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_back.conf
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_chasiss_packet.conf
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_front.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/tsa/isolate.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/tsa/isolate.json
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/tsa/unisolate.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/policies.conf/param_base.json
- src/sonic-bgpcfgd/tests/data/voq_chassis/policies.conf/result_base.conf
- src/sonic-bgpcfgd/tests/test_device_global.py
What I did:
Cherry-pick of PR: https://github.com/sonic-net/sonic-buildimage/pull/16714
> [masft-202205] Support advertisement of Loopback0 of all LC's across all e-BGP peers in TSA mode

- dockers/docker-fpm-frr/TS
- dockers/docker-fpm-frr/TSA
- dockers/docker-fpm-frr/TSB
- dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2
- dockers/docker-fpm-frr/frr/bgpd/templates/voq_chassis/policies.conf.j2
- dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.isolate.conf.j2
- dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.unisolate.conf.j2
- src/sonic-bgpcfgd/bgpcfgd/managers_device_global.py
- src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_chassis_packet_isolate.conf
- src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_chassis_packet_unisolate.conf
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_chasiss_packet.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/policies.conf/result_base.conf
- src/sonic-bgpcfgd/tests/test_device_global.py
What I did:
Cherry-pick of PR: https://github.com/sonic-net/sonic-buildimage/pull/16732
> [msft-202205] Added support of isolating given LC in Chassis with TSA mode

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_ndk.json
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_reboot
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_ndk.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_reboot
This is to manually cherry-pick these two PRs from public master to msft repo 202205 branch that are needed for the Nokia NDK 22.9.21
https://github.com/sonic-net/sonic-buildimage/pull/17483
https://github.com/sonic-net/sonic-buildimage/pull/17378
> Cherry-pick 17483 and 17378 from public master to msft/202205

- platform/checkout/cisco-8000.ini
Signed-off-by: anamehra anamehra@cisco.com
**Release content for Cisco 8000 Chassis platform:**
Fix for Kernel panic seen during qos-sai runs due to issue with Syncd-RPC docker service
Fixed Watchdog issue affected with the kernel version upgrade in 202305
Fix for an issue with gbsyncd failing due to missing sai_query_api_version
Fixed XR OOR/Q100 Nhop group 1K limit
Fix for platform-udev-monitor service start failure after first boot on RP. Fixes an issue with LC reboot after RP first boot.
HBM route scale enablement for Vanguard, Lancer
Change chassis idprom initialization to Eeprom to avoid permissions related failures in ‘show interface status’
Add auto restart parameters to systemd file for platform restart able services
Fix for show platform npu CLIs/ dshell_client startup failure …
> Update cisco-8000.ini to 202305-signed.1.0.2

- src/iccpd/src/mlacp_link_handler.c
ADO 27008034
`set_route_by_linux_route()` is not called by any function within this repo and its submodules, checked on 202106 branch and master branch
```
git grep --recurse-submodules "set_route_by_linux_route"
src/iccpd/src/mlacp_link_handler.c:static void set_route_by_linux_route(struct CSM* csm,
src/iccpd/src/mlacp_link_handler.c:            /*set_route_by_linux_route(csm, set_l3_local_if, 1);*/   /*add static route by linux route tool*/
src/iccpd/src/mlacp_link_handler.c:            /*set_route_by_linux_route(csm, set_l3_local_if, 0);*/    /*del static route by linux route tool*/
```
Remove unused function `set_route_by_linux_route()`
> iccpd - remove unused function

- platform/checkout/cisco-8000.ini
Signed-off-by: anamehra anamehra@cisco.com
Release content for Cisco 8808 platform:
Added kernel patch to skip crash kernel certificate validity check, so kernel crash dumps work.
Fix for show platform npu router route-table cli issue (MIGSMSFT-407)
Fix for Netscan packet get dropped (MIGSMSFT-400)
> Update cisco-8000.ini to 202305-signed.1.0.3

- src/systemd-sonic-generator/Makefile
- src/systemd-sonic-generator/ssg-test.cc
- src/systemd-sonic-generator/systemd-sonic-generator.cpp
- src/systemd-sonic-generator/systemd-sonic-generator.h
Replace char* and C string functions with C++ strings.
- Microsoft ADO **27252906**:
> [ssg]: Use C++ strings for text handling (#18596)

- src/systemd-sonic-generator/Makefile
- src/systemd-sonic-generator/ssg-test.cc
- src/systemd-sonic-generator/systemd-sonic-generator.cpp
- src/systemd-sonic-generator/systemd-sonic-generator.h
Replace char* and C string functions with C++ strings.
Manual cherry-pick of https://github.com/sonic-net/sonic-buildimage-msft/pull/325
> [202205][ssg]: Use C++ strings for text handling

- src/sonic-yang-models/tests/yang_model_tests/tests/buffer_pool.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/buffer_pool.json
- src/sonic-yang-models/yang-models/sonic-buffer-pool.yang
This is to back port the changes from : (https://github.com/sonic-net/sonic-buildimage/pull/18956)
to the MSFT repo 202205 branch.
For details, please refer to the original PR.
> [yang]: adding Buffer pool enum type both for sonic chassis (#18956)

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/pmon_daemon_control.json
Cherry-pick  PR https://github.com/sonic-net/sonic-buildimage/pull/19733 to MSFT Repo 202205 branch
This PR will enable to Psud in LC to address this issue. Fixes https://github.com/sonic-net/sonic-buildimage/issues/19535
Cherry-pick  PR https://github.com/sonic-net/sonic-buildimage/pull/19733 to MSFT Repo 202205 branch.  
Based on the snmp_agent common handling, it requires to enable the Pusd on the LC to set the "psu_num": 0 (as in the below entry) to allow the mibwalk handle the return value correctly. Enable the Psud on the LC although there is no PSU in LC.  
1. Executes "docker exec -it snmp snmpwalk -v2c -c 127.0.0.1 1.3.6.1.4.1.9.9.117.1.1.2.1"
2. Check the syslog, there should not any error in the syslog which is related to this MIBwalk.
> Cherry pick: [Nokia][snmpwalk] Fix the snmpwalk cefcFruPowerStatusTable on Nokia LC platform #19733

- dockers/docker-macsec/Dockerfile.j2
It's required that sonic 202205 to use bookworm macsec container. The reason is to utilize 202405 macsec container which uses symcrypt with provider + engine support for openssl so when 202405 macsec (hardware + macsec control plane) is FIPS certified we can declare that chassis deploying sonic 202205 is FIPS complaint with its macsec solution. 
Another requirement is to have macsec container runs in FIPS mode always.
1) Have macsec bookworm container available on public docker repo: publicmirror.azurecr.io. This bookworm container was taking from 202405 daily build repository.
2) Override /etc/fips/fips_enable to have value 1 during docker image build. 
3) It's found that the cli plugins in bookworm container has slight issue to work under 202205. For …
> Use bookworm macsec container for 2205.

- dockers/docker-fpm-frr/frr/bgpd/templates/voq_chassis/instance.conf.j2
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_all_v4.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_all_v6.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_base_v4.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_base_v6.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_shutdown_v4_1.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_shutdown_v4_2.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_shutdown_v6_1.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_shutdown_v6_2.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_timers_v4_1.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_timers_v4_2.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_timers_v6_1.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_timers_v6_2.conf
This is the cherry-pick PR for PR: https://github.com/sonic-net/sonic-buildimage/pull/20189
* Change the Hold timer to 7 sec and Keep alive to 2 sec for i-BGP session in VOQ Chassis
> [VOQ Chassis] Reduce the i-BGP Keep alive and Hold timer value (#20189)

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/buffers_defaults_t2.j2
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cq2-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cqm2-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3a-36dm2-c36-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3a-36dm2-d36-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x100g.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x400g.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cq2-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cqm2-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3a-36dm2-c36-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3a-36dm2-d36-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x100g.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x400g.json
This is the cherry-pick PR to pick up PR: https://github.com/sonic-net/sonic-buildimage/pull/20132
-----------------------------------------------------------------------------------------
Why I did it
This change is to restrict lossy queue buffer usage in case of congestion state.
Work item tracking
Microsoft ADO (29315559):
How I did it
Updated alpha from 0 to -4 (400g) & -5 (100g) port speed. This configuration is applied on system port and will be using HWSKU port speed settings.
How to verify it
It is verified using sonic-mgmt tests and running ok.
> [Chassis] Update lossy profile to restrict buffer usage in congestion state (#20132)

- build_debug_docker_j2.sh
- dockers/docker-macsec/Dockerfile-debug.j2
Fix docker-macsec-dbg build failure
```
Unpacking libteamdctl0:amd64 (1.30-1) over (1.31-1) ...
Preparing to unpack .../python3-swsscommon_1.0.0_amd64.deb ...
Unpacking python3-swsscommon (1.0.0) over (1.0.0) ...
Preparing to unpack debs/swss_1.0.0_amd64.deb ...
Unpacking swss (1.0.0) over (1.0.0) ...
Selecting previously unselected package libswsscommon-dbgsym.
Preparing to unpack .../libswsscommon-dbgsym_1.0.0_amd64.deb ...
Unpacking libswsscommon-dbgsym (1.0.0) ...
Selecting previously unselected package libhiredis0.14-dbgsym:amd64.
Preparing to unpack .../libhiredis0.14-dbgsym_0.14.1-1_amd64.deb ...
Unpacking libhiredis0.14-dbgsym:amd64 (0.14.1-1) ...
Selecting previously unselected package swss-dbg.
Preparing to unpack debs/swss-dbg_1.0.0_amd64.deb ...
Unpacking swss-dbg (1.0.0) ... …
```
> [Build] Fix docker-macsec-dbg build failure

- .gitmodules
This reverts commit 08f1083335b0b28eadb7779a9dd5e932dcd72ec9.
> Revert "Update submodule branches to 202411 (#21082)"

- files/build_templates/sonic_debian_extension.j2
- files/image_config/monit/conf.d/sonic-host
- files/image_config/monit/mgmt_oper_status.py
- files/image_config/monit/tests/test_mgmt_oper_status.py
Cherry-pick of changes  in https://github.com/sonic-net/sonic-buildimage/pull/21245
- Microsoft ADO **30279044**:
Remove update of mgmt oper status from sonic-swss
Use monit script to periodically update oper status of mgmt interface.
Verified on Chassis platform
> Add script to periodically update oper status of management interface

- .gitmodules
Move sonic-swss-common to 202412 in .gitmodules, due to further changes required from 202411.
> Move sonic-swss-common to 202412 in .gitmodules

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/yang_model_tests/tests/srv6.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/srv6.json
- src/sonic-yang-models/yang-models/sonic-srv6.yang
Cherry-pick PR for [SRv6 YANG](https://github.com/sonic-net/sonic-buildimage/pull/21175) to resolve the conflict.
----------------------------------------------------------------------------------------------------
Why I did it
To support the addition of two new tables in CONFIG_DB, i.e. SRV6_MY_SIDS and SRV6_MY_LOCATORS, in order to allow configuration for SRv6 in SONiC.
Work item tracking
Microsoft ADO (number only): 30513277
How I did it
I define the YANG model based on SRv6 HLD.
How to verify it
Run the unit tests and build image.
> [YANG] Add srv6 yang model and unit tests

- .gitmodules
Previous update was reverted by automation. 
Update sonic-swss-common submodule to Azure 202412 again.
> Update sonic-swss-common submodule to Azure 202412

- azure-pipelines.yml
Set up PR testing in 202412 branch.
Use Azure/sonic-mgmt.msft as test code repo.
Test by pipeline itself.
> [202412] Set up PR testing in 202412 branch

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- src/sonic-device-data/tests/permitted_list
With the current fap initialization sequence, multiple faps in a modular system could come up with  stand alone mode. This is not a recommended configuration.  It might mess up the global clock and might ends up with traffic issue.  
https://github.com/sonic-net/sonic-buildimage/issues/21866
This change adds a required minimum number of links have to be ready before enabling traffic on a fap, which based on the guidance should be able to guarantee the faps in a modular system can form a proper topology.
We manually tested image on a modular system and the topology after boot up looks correct, and there is no more than 1 fap come up with stand alone mode.  We also tested traffic on our system setup and all looks good so far. 
- Microsoft ADO **31597072**:
port this PR from master …
> Add link requirement per sku before enabling traffic on a fap

- src/sonic-frr/patch/0081-bgpd-Optimize-evaluate-paths-for-a-peer-going-down.patch
- src/sonic-frr/patch/0082-Revert-bgpd-upon-if-event-evaluate-bnc-with-matching.patch
- src/sonic-frr/patch/series
Cherry-pick of the following PRs
1) https://github.com/sonic-net/sonic-buildimage/pull/21751
2) https://github.com/sonic-net/sonic-buildimage/pull/21805 
Cherry-pick and resolve conflicts
Running sonic-mgmt tests
> [BGP]Optimize BGP during peer down as well has avoid handling duplicate link up

- platform/checkout/cisco-8000.ini
Release notes:
* LC RMA support script
* Slot number change to use front panel numbers required for show chassis module CLI
* Increased headroom size of backplane ports to avoid headroom drop on longlink linecard
* Enable ECN marking on fabric card when fabric card backplane port is congested. Even though, fabric card does L2 forwarding, the feature will mark ECN bits in the IP (L3 header) during congestion, when this feature is enabled
> Update cisco-8000.ini to 202405.1.2.1 release

- files/build_templates/docker_image_ctl.j2
As per current design, macvlan IP start with an offset of 10 from miplane Ip subnet base ip on a namespace.
In some platforms this may cause conflict if the LC midplane ip for any slot falls in that range. The IP conflict cause midplane traffic loss.
In Cisco Chassis, macvlan IP may conflict with LC midplane IP range. This conflict causes midplane traffic loss for conflicting ip and affects any LC namespace transaction with Supervisor.
To prevent any conflict, Venddor may provide an offset to be used to generate macvlan IP address to prevent any conflict with midplane IP address.
- Microsoft ADO **(31798758)**:
Added an ip_offset value which Vendor may provide based on their midplane ip range to generate safe IP address for macvlan in …
> [chassis][multi-asic]: Add support for vendor LC ip range for macvlan  ip (#22008)

- dockers/docker-orchagent/ipinip.json.j2
Setting decap DSCP mode to pipe for Nvidia platforms.
Updating ipinip.json with platform check
Loading in the device and verifying tunnel is created with dscp_mode as pipe
> [202412]Changing dscp mode in tunnel decap table to pipe for Nvidia platforms

- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/buffers.json.j2
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/buffers_defaults_objects.j2
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/buffers_defaults_t0.j2
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/buffers_defaults_t1.j2
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/buffers_dynamic.json.j2
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/hwsku.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/media_settings.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/optics_si_settings.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/pg_profile_lookup.ini
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/port_config.ini
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/qos.json.j2
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/sai.profile
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/sai_4280.xml
- files/build_templates/docker_image_ctl.j2
- files/image_config/monit/container_checker
- files/initramfs-tools/union-mount.j2
- installer/default_platform.conf
- platform/checkout/cisco-8000.ini
Code sync sonic-net/sonic-buildimage:202411 => 202412
```
*   875852e7b (HEAD -> code-sync-202412, origin/code-sync-202412) r12f 250330:2343 - Merge remote-tracking branch 'base/202411' into code-sync-202412
|\  
| * e523d5171 (base/202411) mssonicbld 250329:0401 - Fix auditd container monit startup issue (#22012)
| * 0615c4a83 mssonicbld 250329:0325 - [installer] Add CSTATE configuration for the AMD CPU. (#22060)
| * 606ff683d mssonicbld 250328:1601 - [submodule] Update submodule sonic-swss to the latest HEAD automatically (#22159)
| * fb3640419 Aravind-Subbaroyan 250326:1714 - Update cisco-8000.ini (#22154)
| * 869a801f3 mssonicbld 250325:1901 - [submodule] Update submodule sonic-utilities to the latest HEAD automatically (#22127)
| * 81af0affe mssonicbld 250325:1601 - …
```
> [202412] Code sync sonic-net/sonic-buildimage:202411 => 202412

- .gitmodules
Update .gitmodules to checkout 202503 branch for all submodules.
submodule head ref don't need to change.
> [build] Init commit for checkout 202503 branch
