.azure-pipelines/code-merge.yml

Fix code merge azure pipeline to sync 202111 branch

---

.gitmodules

Change the sonic-utilities repo url
Change the submodule src/sonic-utilities url to https://github.com/Azure/sonic-utilities.msft

Change the sonic-utilities repo url

---

dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py
src/sonic-bgpcfgd/setup.py
src/sonic-bgpcfgd/staticroutebfd/main.py
src/sonic-bgpcfgd/staticroutebfd/vars.py
src/sonic-bgpcfgd/tests/test_static_rt.py
src/sonic-bgpcfgd/tests/test_static_rt_bfd.py

Double commit the PRs from sonic-net/sonic-buildimage.
Original PR for staticroutebfd:
https://github.com/sonic-net/sonic-buildimage/pull/13789
And a fix for staticroutebfd:
https://github.com/sonic-net/sonic-buildimage/pull/15269

Double commit #13789 and #15269 from sonic-net/sonic-buildimage

---

src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py
src/sonic-bgpcfgd/tests/test_static_rt.py

Double commit the PR from sonic-net/sonic-buildimage.
Original PR for staticroutebfd:
https://github.com/sonic-net/sonic-buildimage/pull/15575

[staticroutebfd] fix static route uninstall issue

---

platform/checkout/cisco-8000.ini

Signed-off-by: anamehra anamehra@cisco.com

Update cisco-8000.ini to 202205.main.0.8

---

src/sonic-bgpcfgd/staticroutebfd/vars.py
src/sonic-bgpcfgd/tests/test_static_rt_bfd.py

Double commit the PR from sonic-net/sonic-buildimage.
Original PR for staticroutebfd:
https://github.com/sonic-net/sonic-buildimage/pull/16450

[staticroutebfd] change bfd to singlehop 

---

platform/checkout/cisco-8000.ini

Update cisco-8000.ini to 202205.3.2.1 drop

---

platform/checkout/cisco-8000.ini

Update cisco-8000.ini to 202205.3.2.2 drop

---

platform/checkout/cisco-8000.ini

Update cisco-8000.ini to ver 202305-signed.1.0.1

---

.gitmodules

Change to use sonic-platform-common.msft and sonic-platform-daemons.msft submodule.

---

platform/checkout/cisco-8000.ini

Pick up Cisco Platform code drop for 8800 on 202305 branch

Update cisco-8000.ini to pick up 202305-signed.1.0.4 for Cisco 8808 platform

---

.gitmodules

Update gitmodules ref to msft repo.

---

.gitmodules

Update submodule branches to 202412 and 202411 if not forked.

Update submodule branches to 202412 and 202411 if not forked.

---

platform/checkout/cisco-8000.ini

Fixed issue: "PSUD DB data keys is not cleared on daemon stop"
Fixed LA error: "'/usr/share/sonic/hwsku/context_config.json': [json.exception.parse_error.101] parse error at line 20"

Update cisco-8000.ini to 202405.1.1.2 release

---

platform/checkout/cisco-8000.ini

Release Content
Fixed appdemo process crash.
Fixed BFD ACL rule generation for internal portchannels using production graph.

Update cisco-8000.ini to 202405.1.1.3 release.

---

files/image_config/constants/constants.yml
src/sonic-config-engine/tests/sample_output/py2/bgpd_frr.conf
src/sonic-config-engine/tests/sample_output/py2/bgpd_frr_bmp.conf
src/sonic-config-engine/tests/sample_output/py2/bgpd_frr_dualtor.conf
src/sonic-config-engine/tests/sample_output/py2/bgpd_quagga.conf
src/sonic-config-engine/tests/sample_output/py2/frr.conf
src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-bgpd.conf
src/sonic-config-engine/tests/sample_output/py3/bgpd_frr.conf
src/sonic-config-engine/tests/sample_output/py3/bgpd_frr_bmp.conf
src/sonic-config-engine/tests/sample_output/py3/bgpd_frr_dualtor.conf
src/sonic-config-engine/tests/sample_output/py3/bgpd_quagga.conf
src/sonic-config-engine/tests/sample_output/py3/frr.conf

Disable graceful restart to support scale scenario. Currently there is an issue with graceful restart configurations where sessions don't come up after reboot. The issue is detailed in https://github.com/FRRouting/frr/issues/17655
Update constants.yml to disable graceful restart feature.
Running image with this change and verify graceful restart configuration is not present.

[BGP]Disable graceful restart to support scale scenario

---

src/sonic-yang-models/tests/yang_model_tests/tests/flex_counter.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
src/sonic-yang-models/yang-models/sonic-flex_counter.yang

Code sync sonic-net/sonic-buildimage:202411 => 202412

[202412] Code sync sonic-net/sonic-buildimage:202411 => 202412

---

platform/checkout/cisco-8000.ini

* Fixed max nhop group setting Q100 asic Line Cards.
* Fixed 'punt packet parse' error causing Loganalyzer failure.
* Fixed do_clear_snoop_config Loganalyzer error

Update cisco-8000.ini to 202405.1.1.4 release

---

platform/checkout/cisco-8000.ini

* Fixed udev event handling to publish CHassis info to LC. Fixes issue where LC stucks during boot waiting for data from RP. (MIGSMSFT-866)

Update cisco-8000.ini to 202405.1.1.6 release

---

platform/checkout/cisco-8000.ini

Release Notes:
Cisco 8800 Chassis:
* Reduced dshell connect start time during boot (Fixed MIGSMSFT-840)
* Fix AOI 40G LR4 workaround for process restart and config reload case (Fixed MIGSMSFT-886)

Update cisco-8000.ini to 202405.1.1.7 release

---

sonic-slave-bullseye/Dockerfile.j2

What I did:
Fix VS Build failure.

Fix VS Build failure

---

platform/checkout/cisco-8000.ini

Cisco 8800 Chassis:
* Fixed LC eth1-midplane and namespace macvlan IP conflict. (MIGSMSFT-926)
* Increased LC check timeout during XR to Sonic Migration. (MIGSMSFT-885)
* Split voq enabled for FC cards. (MIGSMSFT-925)

Update cisco-8000.ini to 202405.1.2.2 release

---

platform/checkout/cisco-8000.ini

Cisco 8800 Chassis:
* Fixed rconsole getting stuck due to duplicate session (MIGSMSFT-927).
* Fixed CLI 'show platform npu bp-interface-map' for backend PortChannel interface mapping.

Update cisco-8000.ini to 202405.1.2.3 release

---

platform/mellanox/mft.mk

Update MFT version to 4.31.0-3004
Update MFT Makefile
Run sonic-mgmt tests

[202412][Mellanox] Update MFT version to 4.31.0-3004

---

platform/checkout/cisco-8000.ini

Update cisco-8000.ini to 202405.1.2.5 release
